
CREATE DATABASE EMPLOYEE_MANAGEMENT;

USE EMPLOYEE_MANAGEMENT;

CREATE TABLE EMPLOYEE_DETAILS(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_NAME VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    SALERY DOUBLE  NOT NULL,
    GENDER VARCHAR(10) NOT NULL
    );
    
INSERT INTO EMPLOYEE_DETAILS (ID, EMPLOYEE_NAME, AGE, SALERY, GENDER)
			VALUES  (1, "ROHIT WAGHOLE", 22, 100000, "MALE"),
					(2, "AKASH CHAUDHARI", 22, 50000, "MALE"),
                    (3, "TEJAS GHODAKHANDE", 21, 150000, "MALE"),
                    (4, "YASH KHOLAPURE" , 23, 75000, "MALE"),
                    (5, "ABHIJEET SHINDE" , 23, 220000, "MALE");
                    
SELECT * FROM EMPLOYEE_DETAILS;
